### PR TITLE
V2024.11.20

### PR DESCRIPTION
**Pull request by Limezy**

### CODE REVIEW

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
@ericgaspar may I have write access to this app ? Trying to make it functionnal again

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by ericgaspar** [comment]
apart from copying the tailwind css file to the server and tweaking files that call cdn... it may not be worth it

**Pull request merged**
